### ISSUE TITLE
issue when make convert_mpas

### ISSUE THREAD

**Issue by Geess126** [mgduda/convert_mpas#6]
Hi, 
I got an issue when compile, the error shows:

( cd src; make FC="gfortran" FFLAGS="-O2 -ffree-form -Wall" FCINCLUDES="-I/my/sam/lib_base_2/include" FCLIBS="-L/my/sam/lib_base_2/lib -lnetcdf -lnetcdff" )
make[1]: Entering directory `/my/sam/kit/convert_mpas/src'
gfortran -o convert_mpas scan_input.o mpas_mesh.o target_mesh.o remapper.o file_output.o copy_atts.o field_list.o timer.o convert_mpas.o -L/my/sam/lib_base_2/lib -lnetcdf -lnetcdff
/my/sam/lib_base_2/lib/libnetcdff.a(nf_attio.o): In function `nf_put_att_text_':
/my/sam/lib_source/netcdf-fortran-4.4.5/fortran/nf_attio.F90:59: undefined reference to `nc_put_att_text'
/my/sam/lib_base_2/lib/libnetcdff.a(nf_attio.o): In function `nf_put_att_text_a_':
/my/sam/lib_source/netcdf-fortran-4.4.5/fortran/nf_attio.F90:92: undefined reference to `nc_put_att_text'
/my/sam/lib_base_2/lib/libnetcdff.a(nf_attio.o): In function `nf_put_att_int1_':
/my/sam/lib_source/netcdf-fortran-4.4.5/fortran/nf_attio.F90:134: undefined reference to `nc_put_att_schar'
/my/sam/lib_base_2/lib/libnetcdff.a(nf_attio.o): In function `nf_put_att_int2_':
/my/sam/lib_source/netcdf-fortran-4.4.5/fortran/nf_attio.F90:183: undefined reference to `nc_put_att_short'
/my/sam/lib_base_2/lib/libnetcdff.a(nf_attio.o): In function `nf_put_att_int_':
/my/sam/lib_source/netcdf-fortran-4.4.5/fortran/nf_attio.F90:226: undefined reference to `nc_put_att_int'
/my/sam/lib_base_2/lib/libnetcdff.a(nf_attio.o): In function `nf_put_att_real_':
/my/sam/lib_source/netcdf-fortran-4.4.5/fortran/nf_attio.F90:269: undefined reference to `nc_put_att_float'
/my/sam/lib_base_2/lib/libnetcdff.a(nf_attio.o): In function `nf_put_att_double_':
/my/sam/lib_source/netcdf-fortran-4.4.5/fortran/nf_attio.F90:305: undefined reference to `nc_put_att_double'
/my/sam/lib_base_2/lib/libnetcdff.a(nf_attio.o): In function `nf_get_att_text_':
/my/sam/lib_source/netcdf-fortran-4.4.5/fortran/nf_attio.F90:337: undefined reference to `nc_get_att_text'
/my/sam/lib_base_2/lib/libnetcdff.a(nf_attio.o): In function `nf_get_att_text_a_':
/my/sam/lib_source/netcdf-fortran-4.4.5/fortran/nf_attio.F90:369: undefined reference to `nc_get_att_text'
/my/sam/lib_base_2/lib/libnetcdff.a(nf_attio.o): In function `nf_get_att_int1_':
/my/sam/lib_source/netcdf-fortran-4.4.5/fortran/nf_attio.F90:406: undefined reference to `nc_get_att_schar'
/my/sam/lib_base_2/lib/libnetcdff.a(nf_attio.o): In function `nf_get_att_int2_':
/my/sam/lib_source/netcdf-fortran-4.4.5/fortran/nf_attio.F90:449: undefined reference to `nc_get_att_short'
/my/sam/lib_base_2/lib/libnetcdff.a(nf_attio.o): In function `nf_get_att_int_':
/my/sam/lib_source/netcdf-fortran-4.4.5/fortran/nf_attio.F90:485: undefined reference to `nc_get_att_int'
/my/sam/lib_base_2/lib/libnetcdff.a(nf_attio.o): In function `nf_get_att_real_':
/my/sam/lib_source/netcdf-fortran-4.4.5/fortran/nf_attio.F90:521: undefined reference to `nc_get_att_float'

Please give me some advice, thanks!

**Comment by Geess126** [comment]
@mgduda

**Comment by Geess126** [comment]
@mgduda @ahijevyc

**Comment by mgduda** [comment]
If you haven't already done so, could you post this question to the support forum at https://forum.mmm.ucar.edu/ ? We generally use GitHub Issues to track problems that can be traced to a specific piece of code, and that can be fixed with a code change, while the forum is used for support inquiries.
