### ISSUE TITLE
Error during make of convert_mpas

### ISSUE THREAD

**Issue by dhanraj125** [mgduda/convert_mpas#8]
Hello,
I am trying to compile convert_mpas and I got the following error

ubuntu@ip-172-31-33-32:~/install_mpas/convert_mpas$ make
( cd src; make FC="gfortran" FFLAGS="-O2 -ffree-form -Wall -DHAVE_NF90_INQ_VARIDS -I/home/ubuntu/install_mpas/libraries/include/ -L/home/ubuntu/install_mpas/libraries/lib/ -lnetcdf -lnetcdff -o sdfsd" FCINCLUDES="" FCLIBS="" )
make[1]: Entering directory '/home/ubuntu/install_mpas/convert_mpas/src'
rm -f scan_input.o scan_input.mod
gfortran -O2 -ffree-form -Wall -DHAVE_NF90_INQ_VARIDS -I/home/ubuntu/install_mpas/libraries/include/ -L/home/ubuntu/install_mpas/libraries/lib/ -lnetcdf -lnetcdff -o sdfsd -c scan_input.F
rm -f mpas_mesh.o mpas_mesh.mod
gfortran -O2 -ffree-form -Wall -DHAVE_NF90_INQ_VARIDS -I/home/ubuntu/install_mpas/libraries/include/ -L/home/ubuntu/install_mpas/libraries/lib/ -lnetcdf -lnetcdff -o sdfsd -c mpas_mesh.F
rm -f target_mesh.o target_mesh.mod
gfortran -O2 -ffree-form -Wall -DHAVE_NF90_INQ_VARIDS -I/home/ubuntu/install_mpas/libraries/include/ -L/home/ubuntu/install_mpas/libraries/lib/ -lnetcdf -lnetcdff -o sdfsd -c target_mesh.F
rm -f remapper.o remapper.mod
gfortran -O2 -ffree-form -Wall -DHAVE_NF90_INQ_VARIDS -I/home/ubuntu/install_mpas/libraries/include/ -L/home/ubuntu/install_mpas/libraries/lib/ -lnetcdf -lnetcdff -o sdfsd -c remapper.F
rm -f file_output.o file_output.mod
gfortran -O2 -ffree-form -Wall -DHAVE_NF90_INQ_VARIDS -I/home/ubuntu/install_mpas/libraries/include/ -L/home/ubuntu/install_mpas/libraries/lib/ -lnetcdf -lnetcdff -o sdfsd -c file_output.F
rm -f copy_atts.o copy_atts.mod
gfortran -O2 -ffree-form -Wall -DHAVE_NF90_INQ_VARIDS -I/home/ubuntu/install_mpas/libraries/include/ -L/home/ubuntu/install_mpas/libraries/lib/ -lnetcdf -lnetcdff -o sdfsd -c copy_atts.F
rm -f field_list.o field_list.mod
gfortran -O2 -ffree-form -Wall -DHAVE_NF90_INQ_VARIDS -I/home/ubuntu/install_mpas/libraries/include/ -L/home/ubuntu/install_mpas/libraries/lib/ -lnetcdf -lnetcdff -o sdfsd -c field_list.F
rm -f timer.o timer.mod
gfortran -O2 -ffree-form -Wall -DHAVE_NF90_INQ_VARIDS -I/home/ubuntu/install_mpas/libraries/include/ -L/home/ubuntu/install_mpas/libraries/lib/ -lnetcdf -lnetcdff -o sdfsd -c timer.F
rm -f convert_mpas.o convert_mpas.mod
gfortran -O2 -ffree-form -Wall -DHAVE_NF90_INQ_VARIDS -I/home/ubuntu/install_mpas/libraries/include/ -L/home/ubuntu/install_mpas/libraries/lib/ -lnetcdf -lnetcdff -o sdfsd -c convert_mpas.F
gfortran -o convert_mpas scan_input.o mpas_mesh.o target_mesh.o remapper.o file_output.o copy_atts.o field_list.o timer.o convert_mpas.o
gfortran: error: scan_input.o: No such file or directory
gfortran: error: mpas_mesh.o: No such file or directory
gfortran: error: target_mesh.o: No such file or directory
gfortran: error: remapper.o: No such file or directory
gfortran: error: file_output.o: No such file or directory
gfortran: error: copy_atts.o: No such file or directory
gfortran: error: field_list.o: No such file or directory
gfortran: error: timer.o: No such file or directory
gfortran: error: convert_mpas.o: No such file or directory
Makefile:15: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/ubuntu/install_mpas/convert_mpas/src'
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 2
 

I am unable to find the reason for this error.
any suggestions will be appreciated.

**Comment by mgduda** [comment]
@dhanraj125 Could you post this question to the MPAS-Atmosphere section of the support forum at https://forum.mmm.ucar.edu/ ? If we determine that there is actually an issue with the code itself, then we can open a GitHub Issue; until then, the support forum would be a better venue for requesting help.

**Comment by dhanraj125** [comment]
ok
